name: Build

on:
  push:
    branches: [ master, integritee-v0.9.4 ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-03-25
          override: true
          target: wasm32-unknown-unknown
      - name: Install llvm-10
        run: sudo apt-get install llvm-10 clang-10
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Build
        run: cargo build --verbose --release
      - name: Upload integritee-collator
        uses: actions/upload-artifact@v2
        with:
          name: integritee-collator
          path: target/release/integritee-collator

  create-artifacts:
    needs: build
    runs-on: ubuntu-20.04
    env:
      CHAIN_SPEC: ${{ matrix.chain }}-${{ matrix.config }}
    strategy:
      matrix:
        chain: [shell, integritee]
        config: [rococo-local, kusama]

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: integritee-collator

      - name: 'Create binaries for artifacts'
        # Note: there is no way to pass the parachain-id to the `build-spec` cmd, which which imposes to set
        # `DEFAULT_PARA_ID=2015` in the `polkadot-parachains/command`.
        run: |
          ./integritee-collator export-genesis-state --chain ${{ env.CHAIN_SPEC }} --parachain-id 2015 >  ${{ env.CHAIN_SPEC }}.state
          ./integritee-collator export-genesis-wasm --chain ${{ env.CHAIN_SPEC }} > ${{ env.CHAIN_SPEC }}.wasm
          ./integritee-collator build-spec --chain ${{ env.CHAIN_SPEC }} --disable-default-bootnode > ${{ env.CHAIN_SPEC }}-spec.json


      - name: Upload Genesis state
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.CHAIN_SPEC }}.state
          path:  ${{ env.CHAIN_SPEC }}.state


      - name: Upload wasm file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.CHAIN_SPEC }}.wasm
          path: ${{ env.CHAIN_SPEC }}.wasm


      - name: Upload build-spec
        uses: actions/upload-artifact@v2
        with:
          name:  ${{ env.CHAIN_SPEC }}.json
          path:  ${{ env.CHAIN_SPEC }}.json